name:  Deploy

on: workflow_dispatch
  
    #branches: [ main ]

jobs:

  deploy-staging:
    name: Deploy to staging
    environment:
      name: Staging
    runs-on: ubuntu-latest
    steps:
      - run: echo Deploy to staging using ${{ secrets.MYSECRET_STAG }}
      
  deploy-QA:
    name: Deploy to QA
    environment:
      name: QA
    needs: [deploy-staging]
    runs-on: ubuntu-latest
    steps:
      - run: echo Deploy to QA using ${{ secrets.MYSECRET_QA }}      
        
  deploy-production:
    name: Deploy to production
    environment:
      name: Production
    needs: [deploy-QA]
    runs-on: ubuntu-latest
    steps:
      - run: echo Deploy to production using ${{ secrets.MYSECRET_PROD }}
